// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must run over Neon's direct (non-pooled) connection —
    // advisory locks used to serialize `migrate deploy` aren't reliable
    // over the pooled connection, which can let concurrent runs interleave
    // and leave partial DDL behind. The app itself still uses the pooled
    // DATABASE_URL directly in src/lib/db.ts, unaffected by this file.
    url: process.env["DIRECT_URL"],
  },
});
